export const EXPLORE_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Premium Artist Oil Paint Set',
    price: '$89.00',
    category: 'Colours & Paints',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400',
    description: 'Professional grade oil paints with intense pigment concentration, offering buttery consistency and excellent lightfastness.',
  },
  {
    id: 'prod-2',
    name: 'Sable Fine Detail Brush Pack',
    price: '$24.50',
    category: 'Brushes & Tools',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400',
    description: 'Handcrafted pure red sable brushes. Excellent spring, snap, and point retention for precision watercolour and miniature painting.',
  },
  {
    id: 'prod-3',
    name: 'Heavyweight Linen Canvas 16x20',
    price: '$34.00',
    category: 'Canvas & Surfaces',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=400',
    description: 'Double-primed Belgian linen canvas on sturdy pine wood stretcher bars. Suitable for acrylics and heavy oils.',
  },
  {
    id: 'prod-4',
    name: 'Hardbound Mixed Media Sketchbook',
    price: '$18.90',
    category: 'Stationery',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?q=80&w=400',
    description: '200gsm acid-free cream paper with hardbound linen cover, perfect for sketching, ink washes, and light watercolours.',
  },
];

export const EXPLORE_SPACES = [
  {
    id: 'space-1',
    name: 'Natural Light Loft Studio',
    capacity: 'Up to 6 artists',
    duration: 'Full Day Access',
    price: '$120.00',
    availability: 'Available Today',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=400',
    description: 'Beautiful industrial loft featuring 14ft floor-to-ceiling windows facing north for perfect constant natural light. Equipped with heavy-duty metal easels.',
  },
  {
    id: 'space-2',
    name: 'Ceramic & Pottery Workshop Space',
    capacity: 'Up to 10 artists',
    duration: 'Hourly Access (Min 2h)',
    price: '$35.00 / hr',
    availability: 'Next slot: 2:00 PM',
    image: 'https://images.unsplash.com/photo-1565192647048-f997ed87f5e2?q=80&w=400',
    description: 'Fully functional ceramics studio equipped with 8 electric pottery wheels, clay pug mill, and a high-fire electric kiln.',
  },
  {
    id: 'space-3',
    name: 'Private Art Exhibition Room',
    capacity: 'Up to 50 guests',
    duration: 'Daily Access',
    price: '$450.00',
    availability: 'Booking essential',
    image: 'https://images.unsplash.com/photo-1531050171654-a78b74134a57?q=80&w=400',
    description: 'Premium gallery hall with adjustable track spotlighting, white floating walls, and built-in projection system for digital exhibitions.',
  },
];

export const EXPLORE_SERVICES = [
  {
    id: 'serv-1',
    title: 'Custom Artwork Commission',
    icon: 'brush-outline',
    description: 'Connect with renowned resident artists to paint custom portraits, murals, or landscape designs tailored to your living space.',
    details: 'Commission custom paintings in oil, acrylic, or digital medium. Includes consultation session, layout drafts, and custom framing.',
  },
  {
    id: 'serv-2',
    title: 'Professional Canvas Framing',
    icon: 'cut-outline',
    description: 'Premium museum-grade custom framing options for canvases, paper prints, and shadow boxes. Acid-free backings.',
    details: 'Handcrafted solid wood frames (Oak, Walnut, Maple) with museum-grade UV protection glass and custom matting sizes.',
  },
  {
    id: 'serv-3',
    title: 'Giclée Fine Art Printing',
    icon: 'print-outline',
    description: 'Archival printing services on heavy cotton rag paper or textured canvas using pigment-based inks with true-colour depth.',
    details: 'High-resolution drum scanning up to 2400dpi, professional colour calibration, and print sizes up to 44 inches wide.',
  },
  {
    id: 'serv-4',
    title: 'Creative Art Projects & Installations',
    icon: 'color-palette-outline',
    description: 'Bespoke corporate installation design, art murals for commercial spaces, and sculpture installations.',
    details: 'Full project management including workspace site visits, mockups, logistics, installation, and lighting alignment.',
  },
];

export const EXPLORE_EVENTS = [
  {
    id: 'event-1',
    name: 'Impressionist Oil Masterclass',
    instructor: 'Arthur Pendelton',
    date: 'July 25, 2026',
    time: '2:00 PM - 5:00 PM',
    seats: 4,
    price: '$75.00',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=400',
    description: 'Learn loose brushwork techniques, color theory, and light capture principles of the Impressionists in this hands-on workshop.',
  },
  {
    id: 'event-2',
    name: 'Intro to Ceramic Glazing & Kiln Firing',
    instructor: 'Yuri Kovich',
    date: 'July 28, 2026',
    time: '11:00 AM - 2:00 PM',
    seats: 7,
    price: '$90.00',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=400',
    description: 'Explore hand-building clay models, applying underglazes, dipping in translucent glazes, and understanding electric kiln firing cycles.',
  },
  {
    id: 'event-3',
    name: 'Modern Abstract Composition',
    instructor: 'Sarah Jenkins',
    date: 'Aug 02, 2026',
    time: '6:00 PM - 9:00 PM',
    seats: 12,
    price: '$60.00',
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=400',
    description: 'Ditch the brushes and paint with palette knives, squeegees, and acrylic inks to create an expressive modern abstract painting.',
  },
];

export const EXPLORE_RECOMMENDED = [
  {
    id: 'rec-1',
    type: 'product',
    title: 'Sable Fine Detail Brush Pack',
    price: '$24.50',
    category: 'Brushes & Tools',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400',
    targetId: 'prod-2',
  },
  {
    id: 'rec-2',
    type: 'space',
    title: 'Natural Light Loft Studio',
    price: '$120.00',
    category: 'Studio Space',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=400',
    targetId: 'space-1',
  },
  {
    id: 'rec-3',
    type: 'event',
    title: 'Impressionist Oil Masterclass',
    price: '$75.00',
    category: 'Workshop',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=400',
    targetId: 'event-1',
  },
  {
    id: 'rec-4',
    type: 'service',
    title: 'Professional Canvas Framing',
    price: 'Varies',
    category: 'Custom Service',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=400',
    targetId: 'serv-2',
  },
];
