export const DUMMY_PRODUCTS = [
  // Colours & Paints
  {
    id: 1,
    name: 'Premium Artist Oil Paint Set',
    price: 89.00,
    category: 'Colours & Paints',
    rating: 4.8,
    reviews: 142,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400',
    description: 'Professional grade oil paints with intense pigment concentration, offering buttery consistency and excellent lightfastness.',
    stock: 12,
    featured: true,
    popular: true
  },
  {
    id: 2,
    name: 'Acrylic Paint Kit - 24 Colours',
    price: 35.00,
    category: 'Colours & Paints',
    rating: 4.7,
    reviews: 98,
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=400',
    description: 'Rich, creamy acrylic paints that glide onto surfaces smoothly, drying quickly to a durable satin finish.',
    stock: 25,
    featured: false,
    popular: true
  },
  {
    id: 3,
    name: 'Metallic Acrylic Paint Set',
    price: 28.00,
    category: 'Colours & Paints',
    rating: 4.6,
    reviews: 54,
    image: 'https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?q=80&w=400',
    description: 'Shimmering metallic colors including Gold, Silver, Bronze, and Copper. High coverage and brilliant sheen.',
    stock: 8,
    featured: false,
    popular: false
  },
  {
    id: 4,
    name: 'Professional Watercolour Pan Set',
    price: 55.00,
    category: 'Colours & Paints',
    rating: 4.9,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&fit=crop',
    description: 'Artist-quality watercolour half-pans in a sleek metal travel tin. Superior transparency and color strength.',
    stock: 15,
    featured: true,
    popular: true
  },
  {
    id: 5,
    name: 'Gouache Paint Set - 18 Tubes',
    price: 32.50,
    category: 'Colours & Paints',
    rating: 4.5,
    reviews: 73,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&q=50',
    description: 'Opaque watercolours with a beautiful matte finish. Perfect for designers, illustrators, and fine artists.',
    stock: 19,
    featured: false,
    popular: false
  },
  {
    id: 6,
    name: 'Fluorescent Neon Paint Set',
    price: 22.50,
    category: 'Colours & Paints',
    rating: 4.4,
    reviews: 39,
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=400&fit=scale',
    description: 'Glow under UV blacklight. Highly vibrant colors that add neon punch to your canvases and crafts.',
    stock: 14,
    featured: false,
    popular: false
  },

  // Brushes & Tools
  {
    id: 7,
    name: 'Sable Fine Detail Brush Pack',
    price: 24.50,
    category: 'Brushes & Tools',
    rating: 4.9,
    reviews: 188,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400',
    description: 'Handcrafted pure red sable brushes. Excellent spring, snap, and point retention for precision watercolour and miniature painting.',
    stock: 30,
    featured: true,
    popular: true
  },
  {
    id: 8,
    name: 'Synthetic Acrylic Brush Set',
    price: 18.00,
    category: 'Brushes & Tools',
    rating: 4.6,
    reviews: 112,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400&fit=crop',
    description: 'Durable nylon brushes suited for acrylic and heavy-body paints. Pack includes flats, rounds, and fan brushes.',
    stock: 45,
    featured: false,
    popular: true
  },
  {
    id: 9,
    name: 'Hog Bristle Oil Paint Brushes',
    price: 29.00,
    category: 'Brushes & Tools',
    rating: 4.7,
    reviews: 67,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400&q=70',
    description: 'Stiff Chinese hog bristles that hold heavy oil paints with ease. Long wooden handles for perfect easel balance.',
    stock: 11,
    featured: false,
    popular: false
  },
  {
    id: 10,
    name: 'Palette Knives & Spatula Set',
    price: 15.00,
    category: 'Brushes & Tools',
    rating: 4.8,
    reviews: 82,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&fit=crop&q=60',
    description: 'Stainless steel blades with flexible, comfortable wooden handles. Ideal for impasto techniques and paint mixing.',
    stock: 22,
    featured: false,
    popular: false
  },
  {
    id: 11,
    name: 'Airbrush Compression Gun Kit',
    price: 110.00,
    category: 'Brushes & Tools',
    rating: 4.7,
    reviews: 49,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400&a=1',
    description: 'Complete airbrush kit with mini compressor. Dual-action gravity feed spray gun for model painting, makeup, and illustration.',
    stock: 5,
    featured: true,
    popular: false
  },
  {
    id: 12,
    name: 'Detail Painting Micro-Brushes',
    price: 13.50,
    category: 'Brushes & Tools',
    rating: 4.8,
    reviews: 95,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400&q=40',
    description: 'Ultra-fine detailing brushes (sizes 000 to 0) designed specifically for paint-by-numbers, miniatures, and figurines.',
    stock: 40,
    featured: false,
    popular: true
  },

  // Canvas & Surfaces
  {
    id: 13,
    name: 'Heavyweight Linen Canvas 16x20',
    price: 34.00,
    category: 'Canvas & Surfaces',
    rating: 4.7,
    reviews: 156,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=400',
    description: 'Double-primed Belgian linen canvas on sturdy pine wood stretcher bars. Suitable for acrylics and heavy oils.',
    stock: 18,
    featured: true,
    popular: true
  },
  {
    id: 14,
    name: 'Stretched Cotton Canvas Multipack',
    price: 26.00,
    category: 'Canvas & Surfaces',
    rating: 4.5,
    reviews: 104,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=400&c=1',
    description: 'Pack of 5 stretched 100% cotton canvases (8x10 to 12x16). Acid-free gesso primed, ready to paint.',
    stock: 30,
    featured: false,
    popular: true
  },
  {
    id: 15,
    name: 'Watercolor Paper Pad 300gsm',
    price: 19.50,
    category: 'Canvas & Surfaces',
    rating: 4.8,
    reviews: 121,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=400&q=50',
    description: 'Cold-pressed, acid-free, 100% cotton watercolour paper sheets. Resists buckling and tearing under heavy wet media.',
    stock: 25,
    featured: false,
    popular: true
  },
  {
    id: 16,
    name: 'Mixed Media Art Board Set',
    price: 22.00,
    category: 'Canvas & Surfaces',
    rating: 4.6,
    reviews: 43,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=400&f=1',
    description: 'Rigid art boards with textured surfaces. Perfect for combining charcoal, gouache, pastels, and collages.',
    stock: 15,
    featured: false,
    popular: false
  },
  {
    id: 17,
    name: 'Wooden Painting Panel (Pack of 3)',
    price: 27.50,
    category: 'Canvas & Surfaces',
    rating: 4.7,
    reviews: 31,
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?q=80&w=400&p=3',
    description: 'Smooth birch wood panels. Exceptional stability for detailed fine-line work, pouring paints, and encaustic medium.',
    stock: 10,
    featured: true,
    popular: false
  },

  // Stationery
  {
    id: 18,
    name: 'Hardbound Mixed Media Sketchbook',
    price: 18.90,
    category: 'Stationery',
    rating: 4.6,
    reviews: 145,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?q=80&w=400',
    description: '200gsm acid-free cream paper with hardbound linen cover, perfect for sketching, ink washes, and light watercolours.',
    stock: 20,
    featured: false,
    popular: true
  },
  {
    id: 19,
    name: 'Professional Drawing Pencil Set',
    price: 14.00,
    category: 'Stationery',
    rating: 4.8,
    reviews: 167,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&s=1',
    description: '12 high-grade graphite pencils (from 6B to 4H). Perfect for fine sketching, realistic shading, and technical drafting.',
    stock: 35,
    featured: false,
    popular: true
  },
  {
    id: 20,
    name: 'Dual Tip Brush Marker Pens',
    price: 39.90,
    category: 'Stationery',
    rating: 4.7,
    reviews: 232,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&m=1',
    description: '36 vibrant colors with flexible nylon brush tips on one end and fine bullet tips on the other. Water-based blendable ink.',
    stock: 17,
    featured: true,
    popular: true
  },
  {
    id: 21,
    name: 'Premium Sketching Charcoal Kit',
    price: 12.50,
    category: 'Stationery',
    rating: 4.5,
    reviews: 58,
    image: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?q=80&w=400&c=1',
    description: 'Assortment of vine and compressed charcoal sticks, blending stumps, and kneaded erasers for expressive sketching.',
    stock: 28,
    featured: false,
    popular: false
  },
  {
    id: 22,
    name: 'Refillable Fountain Pen Set',
    price: 34.90,
    category: 'Stationery',
    rating: 4.6,
    reviews: 79,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&f=1',
    description: 'Elegant fountain pen with fine, medium iridium nibs and multi-colour ink cartridges in a handcrafted wooden gift case.',
    stock: 14,
    featured: false,
    popular: false
  },

  // Creative Kits
  {
    id: 23,
    name: 'Watercolour Painting Starter Kit',
    price: 45.00,
    category: 'Creative Kits',
    rating: 4.8,
    reviews: 110,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=400',
    description: 'Complete watercolour painting starter kit. Includes 12 essential half-pans, watercolor paper pad, and 3 travel brushes.',
    stock: 15,
    featured: true,
    popular: true
  },
  {
    id: 24,
    name: 'Macrame Craft Hanging Kit',
    price: 25.00,
    category: 'Creative Kits',
    rating: 4.4,
    reviews: 42,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=400&m=1',
    description: 'Includes 100m of premium cotton cord, wooden rings, beads, and step-by-step instruction booklet for beautiful wall art.',
    stock: 20,
    featured: false,
    popular: false
  },
  {
    id: 25,
    name: 'DIY Pottery & Clay Sculpting Kit',
    price: 42.00,
    category: 'Creative Kits',
    rating: 4.7,
    reviews: 86,
    image: 'https://images.unsplash.com/photo-1565192647048-f997ed87f5e2?q=80&w=400',
    description: 'Air-dry clay, dynamic sculpting wire loops, loop scrapers, ribs, and step-by-step instructions. Ideal for hand-building.',
    stock: 12,
    featured: true,
    popular: true
  },
  {
    id: 26,
    name: 'Modern Calligraphy Practice Kit',
    price: 29.90,
    category: 'Creative Kits',
    rating: 4.6,
    reviews: 64,
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=400',
    description: 'Includes oblique pen holder, Nikko G metal nibs, black calligraphic ink, and trace-ruled practice booklet.',
    stock: 18,
    featured: false,
    popular: false
  },
  {
    id: 27,
    name: 'Linocut Block Printing Starter Kit',
    price: 38.00,
    category: 'Creative Kits',
    rating: 4.8,
    reviews: 52,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=400&l=1',
    description: 'Equipped with linoleum cutters, rollers, block printing ink, and reusable linoleum pads for printing stamps and cards.',
    stock: 10,
    featured: false,
    popular: true
  },

  // Art Supplies
  {
    id: 28,
    name: 'Adjustable Wooden Studio Easel',
    price: 95.00,
    category: 'Art Supplies',
    rating: 4.8,
    reviews: 74,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&e=1',
    description: 'Solid beechwood H-frame studio easel. Tilts completely flat for watercolours and stands up to 90 inches high.',
    stock: 7,
    featured: true,
    popular: true
  },
  {
    id: 29,
    name: 'Studio Storage Cart & Organizer',
    price: 68.00,
    category: 'Art Supplies',
    rating: 4.7,
    reviews: 51,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&o=1',
    description: 'Three-tier rolling cart with steel mesh baskets. Perfect for storing paints, mediums, brushes, and sketchbooks.',
    stock: 13,
    featured: false,
    popular: false
  },
  {
    id: 30,
    name: 'Portable Desktop Easel Box',
    price: 45.00,
    category: 'Art Supplies',
    rating: 4.6,
    reviews: 90,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&p=1',
    description: 'Compact tabletop sketchbox easel. Built-in storage drawer with divided compartments for on-the-go sketching.',
    stock: 22,
    featured: false,
    popular: true
  },
  {
    id: 31,
    name: 'Glass Paint Mixing Palette',
    price: 16.00,
    category: 'Art Supplies',
    rating: 4.7,
    reviews: 63,
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=400&g=1',
    description: 'Tempered glass palette with smooth, easy-to-clean surface. Fits perfectly on tabletops or inside sketching boxes.',
    stock: 30,
    featured: false,
    popular: false
  },
  {
    id: 32,
    name: 'Brush Washer and Cleaner Tub',
    price: 12.00,
    category: 'Art Supplies',
    rating: 4.5,
    reviews: 104,
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=400&w=1',
    description: 'Stainless steel airtight container with removable spiral holder and interior cleaning screen. Keeps solvent clean.',
    stock: 25,
    featured: false,
    popular: false
  }
];
